Fix build errors for SQL compiler GUI
Recently, the compiler GUI started giving error messages during the build.
Note that this does not cause the overall build to fail.

Thanks to Howard for suggesting the fix, making sure that we use
/usr/bin/g++ to compile the GUI as we do for the rest of the code.
I tried using $(CC) instead of /usr/bin/g++ but that did not work.

Here are some of the error messages we saw, complaining about C++
syntax that was either outdated or relatively new:

In file included from ../export/NAStringDef.h:64,
                 from ../common/NAString.h:39,
                 from ../common/ComObjectName.h:55,
                 from ../common/CmpCommon.h:48,
                 from ../optimizer/ObjectNames.h:41,
                 from ../optimizer/ValueDesc.h:38,
                 from ../optimizer/GroupAttr.h:41,
                 from CommonSqlCmpDbg.h:34,
                 from MainWindow.h:24,
                 from MainWindow.cpp:18:
../export/FBString.h: In function ‘void folly::fbstring_detail::pod_fill(Pod*, Pod*, T)’:
../export/FBString.h:133: error: ISO C++ forbids declaration of ‘ee’ with no type
 auto const ee = b + ((e – b) & ~7u);

In file included from ../common/ComSecurityKey.h:24,
                 from ../optimizer/NATable.h:43,
                 from ../optimizer/ColStatDesc.h:42,
                 from ../optimizer/EstLogProp.h:49,
                 from ../optimizer/GroupAttr.h:42,
                 from CommonSqlCmpDbg.h:34,
                 from MainWindow.h:24,
                 from MainWindow.cpp:18:
../sqlcomp/PrivMgrDefs.h: At global scope:
../sqlcomp/PrivMgrDefs.h:61: error: expected identifier before ‘class’
  enum class PrivAuthClass {

Change-Id: I5e220b031af988077271179a969bc0724e2ee584